TYPO3:
  Flow:
    security:
      enable: TRUE
      authentication:
        authenticationStrategy: oneToken
        providers:
          DefaultProvider:
            provider: PersistedUsernamePasswordProvider